# Generated by Django 4.0.4 on 2022-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('user', models.CharField(choices=[('ST', 'Student'), ('MT', 'Mentor')], max_length=2)),
            ],
        ),
    ]
