# Generated by Django 4.0.4 on 2022-06-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.course')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_type',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduler.mentor')),
                ('capacity', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.user')),
                ('section_name', models.ManyToManyField(to='scheduler.section')),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.user'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('P', 'Present'), ('UA', 'Unexcused Absesnce'), ('EA', 'Excused Absence')], max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.student')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='student_in_section',
            field=models.ManyToManyField(to='scheduler.student'),
        ),
    ]
