# Generated by Django 4.0.4 on 2022-06-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_course_mentor_rename_name_text_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
